[package]
name = "rs-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
indicatif = "0.16"
futures-util = "0.3"
